### ISSUE TITLE
My lsblk doesn't have a '-p' option, so this doesn't run for me anymore.

### ISSUE THREAD

**Issue by jbaber** [jamielinux/bashmount#12] opened 2015-01-28 23:27 UTC
I tried to find a manpage in google that did so I could guess what it was for and fix, but I can't find one.

Ubuntu 14.03 LTS

**Comment by jamielinux** [comment] 2015-01-29 14:12
Duplicate of issue #9 and issue #10. Your version of lsblk is too old. Ubuntu 14.10 and above have the version required.

**Closed by jamielinux** 2015-01-29 14:12 UTC
